### ISSUE TITLE
4.7.0-beta prep

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1098]
Things to do in the final push:

- [x] Permit `remove_extra_templates` checkbox to be remembered via hidden pref (@bloatware).
- [x] Permit pophelp on multi-edit items (see remove_extra_templates checkbox): delegated AJAX invocation (@bloatware).
- [x] Fix theme messages, as they don't replace `{list}` properly right now (anyone).
- [x] When trying to import a skin that doesn't exist from the filesystem (theme is in DB but has not yet been exported) the wrong error message is thrown (NicolasGraph).
- [x] Add Search by Description on Themes panel (Bloke / anyone).
- [x] Finalise theme callbacks (Bloke).
- [x] txp:output_form with theme support - #1084 
- [x] Rename default theme and manifest in setup directory to something sexier (anyone).
- [x] Fix plugin language string provision when running from cache (Bloke).
- [x] Test and merge in multi-site branch (@petecooper / anyone).
- [x] Checksums (anyone).
- [x] HISTORY.txt (anyone).
- [x] Remove or deal with `setup_autoinstall_text` - https://github.com/textpattern/textpattern/issues/1100 (anyone)
- [x] Documentation [textpattern/textpattern.github.io#75] (everyone).
- [x] XML Injection Denial of Service issue - https://github.com/textpattern/textpattern/issues/1141
- [x] Diagnostics panel - translated strings in report - https://github.com/textpattern/textpattern/issues/1139
- [x] Plugin help files rendering - https://github.com/textpattern/textpattern/issues/908

[Permit theme and private/public separation in multi-site - see [this discussion](https://github.com/textpattern/textpattern/commit/c95016cf2d680348d4dcea57764bd05966ecbd70#commitcomment-25940041) (@makss / @bloatware ) - Deferring this. It can be done now via plugins and is forwards-compatible with whatever system we introduce.]

I think that's all. The assignees are not set in stone. Please feel free to take any of these you fancy and tick them off when done :-)

P.S. There's a lot of stuff that can be improved in the under-the-hood themes implementation. Primarily optimsations and stack usage improvements (there are lots of repeated calls to functions that can be reduced). We could do this now, but Nicolas is working on another iteration with far fewer statics. This work isn't vital for beta - it'll be folded in for -rc or final so I'm tempted to leave the unoptimised code there for now to save extra work later. I may do some of this when I finalize the callbacks, if it warrants changes.

**Comment by petecooper** [comment]
Happy days! Will see what I can do.

**Comment by petecooper** [comment]
>Rename default theme and manifest in setup directory to something sexier (anyone).

It's grey, so… Shades.

If the default theme is going to stay largely the same visually, then does it need a sexy or iterative (hi, [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/), we see you) name?

I mean, it's a default theme. It's called…default. That's a pretty good name, actually.

**Comment by Bloke** [comment]
> If the default theme is going to stay largely the same visually, then does it need a sexy or iterative name?

It could be the same name for each version, but as we evolve it - to take advantage of new tags and update the inline docs even if it remains visually the same - it'd be nice to have separate downloads on the themes repo to show progression, and to cater for people who are running old stock. Just a marketing thing really.

The issue with it being called 'default' is that it'll clash with your own site's theme which will be named `default` during the upgrade process. So if you download othe stock one you won't be able to drop it in your themes directory and import it if you've already exported yours, as the names will clash.

Worse, if you haven't exported yours and you drop the Txp default one in the themes directory and import, you'll trash your site's templates (unless you've had the foresight to rename yours to something better than 'default' first).

It's safer all round to give the default theme a cooler name, even if it's just the uninspiring `txp-4.7.0`. At least it does what it says on the tin and gives people a clue which version it works on!

**Comment by petecooper** [comment]
Ah, now I understand -- thanks, @Bloke.

Anything tangentially related to Hive for a name? I kinda like Teem, but it's too close to 'theme' and just sounds like a dad joke.

**Comment by Bloke** [comment]
I'm sure Phil won't mind the publicity if something Hive-ish is used :-)

Dunno how we'd iterate that next time, but maybe we'll come up with something else by then.

**Comment by Bloke** [comment]
I like *Four Point Seven*, Pete!

**Comment by philwareham** [comment]
@bloke @petecooper guys, please see: https://github.com/textpattern/textpattern/issues/1101

**Comment by petecooper** [comment]
@Bloke - please update OP (I cannot) to append this link to "Documentation (everyone)" – https://github.com/textpattern/textpattern.github.io/issues/75

**Comment by Bloke** [comment]
Done. Hmmm, how does one change the owner of a post so it can be altered by anyone on the team?

**Comment by petecooper** [comment]
I don't think you can. I just don't have edit/write rights to the repo, which is totally fine, but it makes admin work when things like this crop up. No biggie.

**Comment by petecooper** [comment]
I _might_ have some time tomorrow or Friday to ~~Rehash The Bash~~ overhaul the demo site to test out the multisite stuff, so heavy pencil me onto that, please and thank you.

**Comment by bloatware** [comment]
> When trying to import a skin that doesn't exist from the filesystem (theme is in DB but has not yet been exported)

I don't understand what `import` in multi-select means: the selectable themes are already in DB, where should they be imported?

**Comment by bloatware** [comment]
One can only select DB stored themes in multi-edit form, right? What's the point of importing their filesystem copy into DB again? Shouldn't this be called `update` instead?

**Comment by Bloke** [comment]
Actually, it used to be called `update` but I think I changed it to `import` for reasons I now cannot recall (probably because it was the analog of 'export').

You're right, it should probably be called `update` and all multi-edit feedback messages shoulld reflect that, compared with using the `import` selector at the top of the list, which is used for themes that *do not* yet exist in the DB.

Sorry for the stupidity on my part.

**Comment by NicolasGraph** [comment]
That’s why I named it ‘update’ at first…
In fact it override the theme in the DB from the flat files.

**Comment by bloatware** [comment]
I would merely delegate the `update` functionality to *Import theme* selector, without hiding the already imported themes. Otherwise, it's impossible to detect which themes are updatable.

**Comment by Bloke** [comment]
> Otherwise, it's impossible to detect which themes are updatable.
True.

There was talk at first of some indicator logic stating which theme (or even on Pages/Forms/Styles, which individual assets) were "the freshest" out of the disk or DB versions. That fell by the wayside for now, as it makes the UX too complicated and we felt was better functionality deferred to plugins.

The only issues with using the Import theme selector:

* Must be done one at a time. Probably not a major issue for most people, granted!
* Doesn't have the ability to 'completely refresh' (delete and import). It could be added, but then it doesn't apply for first-time imports, We could get round that by detecting if the selected theme is installed and adding the checkbox at that point. The Upload button would move unless we put the checkbox somewhere beneath the selector.
* Would have to have a 'confirm' step added if the theme already exists in the DB. We get that for free wiht multi-edit.

The fact the multi-edit action might not be applicable to the selected items is annoying, but not without precedent in our UI. For example, visit the Sections panel, select all and then use multi-edit 'Delete'. Only those that are not in use will be deleted: the rest will be skipped. Same with import in a way: if you've done a mass-edit in the filesystem, you could select all, choose import, confirm. But any that can't be updated (violating filenames, those that have not yet been exported, etc) just fail while the rest succeed.

Dunno which is best.

**Comment by petecooper** [comment]
Regarding `HISTORY.txt` and checksums, those are two distinct tasks that should really be decoupled. History stuff is updated piecemeal by anyone, and checksums are whoever pilots the release buttons.

On that, I can have a look through the 4.6.2 to present day commits and see if anything substantial is missing.

**Comment by Bloke** [comment]
Split. I think most stuff has been captured in `HISTORY.txt` but if you spot anything else, then that's grand.

**Comment by philwareham** [comment]
Bump. I have no further work for 4.7 release as far as I know. Progress seems to have stalled so just checking what's up? Cheers all!

**Comment by petecooper** [comment]
https://github.com/textpattern/textpattern.github.io/issues/75 is currently complete and closed, so that can be ticked off in OP, please.

**Comment by NicolasGraph** [comment]
I'm finishing the Skin package rework; it's coming.

**Comment by bloatware** [comment]
`Permit theme and private/public separation in multi-site` - I'm a complete n00b to both themes and multi-site, please someone else take it if we wish to release 4.7 this year :-(

**Comment by NicolasGraph** [comment]
I will send [a pull request](https://github.com/NicolasGraph/textpattern/issues/1) to the _themes_ branch tomorrow at the end of the morning.
Could any core dev merge the _dev_ branch into _themes_ in the meanwhile, so I could detect any conflicts?
Thanks a lot.

**Comment by philwareham** [comment]
> Could any core dev merge the dev branch into themes in the meanwhile, so I could detect any conflict?

Great news! Thanks Nicolas. OK, dev merged into themes branch for you as requested.

**Comment by NicolasGraph** [comment]
Thanks @philwareham; [PR sent](https://github.com/textpattern/textpattern/pull/1143).

**Comment by philwareham** [comment]
Hi all, I've merged Nicolas's theme work into the `themes` branch. I haven't got time today to test but if a couple of you could give it a spin and if no serious bugs then merge that into `dev`. Any further amends can then be done there. Thanks!

**Comment by NicolasGraph** [comment]
Thanks @philwareham. There were some informations about few things to fix and textpack strings to alterate in the pull request related message. Should I open dedicated issues to be sure they will be taken into account? I'm not sure other devs will take a look at a closed PR…

**Comment by philwareham** [comment]
Yes please - an issue would be handy.

**Comment by NicolasGraph** [comment]
Done [here](https://github.com/textpattern/textpattern/issues/1145) and [there](https://github.com/textpattern/textpattern/issues/1144).

**Comment by NicolasGraph** [comment]
The following is fixed in the last rework:

> - [x] When trying to import a skin that doesn't exist from the filesystem (theme is in DB but has not yet been exported) the wrong error message is thrown (NicolasGraph).

**Comment by Bloke** [comment]
Sweet, thanks. When we merge themes into dev, we'll clear that down.

**Comment by Bloke** [comment]
The only possible thing to worry about now is the 'delete everything in the theme folder when you delete a theme' issue - see #1154. Not sure the best way to resolve that. Ideas welcome.

As far as I'm concerned, after that we're done here. We can merge themes into dev, give it all a final soak test, then add checksums and it's game on for beta.

Any last requests?

**Comment by NicolasGraph** [comment]
While working on the feature your talking about, I found a bug coming from the way I get template files; the filter does not work correctly. I'm trying to understand and fix.

**Comment by Bloke** [comment]
OK, no worries. Note I changed the themes branch this morning so you'll need to merge with yours to get the latest callback modifications.

I've also added one more thing I forgot to the list in my post above. I'll try and figure out the best way to tackle that later today or tomorrow.

**Comment by NicolasGraph** [comment]
Ok @Bloke, thanks.

**Comment by philwareham** [comment]
Hi. I'm going to merge themes branch into dev later today. Please continue any further theme feature edits there. Users tend to test dev branch above all others so by merging we open testing to a wider group. Thanks.

**Comment by NicolasGraph** [comment]
Ok @philwareham, I just sent a PR for you to merge last changes about `skin_synchronize` behaviour on deletion into _themes_ before merging it into _dev_.

**Comment by philwareham** [comment]
OK, themes now in dev. Thanks Nicholas for the extensive work. Go wild everyone! 🎉🎉🎉

**Comment by philwareham** [comment]
Can we go to beta next week?

**Comment by petecooper** [comment]
Looking at OP, the only outstanding issue is https://github.com/textpattern/textpattern/issues/1084 (which appears to have been partially [mostly?] resolved), and the `HISTORY.txt` stuff can be worked on while the beta(s) are being poked and prodded.

**Comment by philwareham** [comment]
I've written a couple of bits of history and checked that one off - it shouldn't be a blocker to beta release anyway as you're right, history can be written anytime. I think we've covered the major changes in 4.7 but feel free to add more lines if you see fit.

So, just checksums and that output_form issue that I don't understand. So *very* close to beta!!

**Comment by philwareham** [comment]
Oh, there are also these of course:

https://github.com/textpattern/textpattern/milestone/2

**Comment by petecooper** [comment]
Can someone update OP to include https://github.com/textpattern/textpattern/milestone/2 as a meta-issue, or duplicate the descriptions as checkbox items, please and thanks?

**Comment by philwareham** [comment]
Righto.

**Comment by philwareham** [comment]
Just want to add Tagalog to the languages in the morning (someone is translating it right now) and I’m happy for beta to release.

**Comment by Bloke** [comment]
No worries. I've put together a little script in the toolkit to help rebuild the checksums. It could do with being an 'all-in-one' solution instead of the two-steps I have it right now, but I'm not sure if it can be coerced into working that way. Will see what I can see do.

**Comment by petecooper** [comment]
I'm ready to drop in the GitHub URL and beta-demo.textpattern.co will be ready for consumption.

**Comment by philwareham** [comment]
OK, I'm ready for you to go to beta - no further commits from me! 😀🎂🎉🏆

**Comment by philwareham** [comment]
Closing this. We are on it. Will release as soon as we can.

**Comment by petecooper** [comment]
Adding this before I forget – tell me if it's better elsewhere.

The admin-side themes are manually versioned (in `manifest.json`) and they have `-dev` suffixes right now, these probably need to be changed for beta release – I didn't see anything in https://github.com/textpattern/textpattern-toolbelt that covers that process.

**Comment by Bloke** [comment]
Step 3. But a typo shows up as "mainfest" instead of "manifest"

**Comment by petecooper** [comment]
>mainfest

…and that's the search term I used. Thanks for fixing!

**Comment by philwareham** [comment]
Will update theme manifests now, thanks

**Comment by philwareham** [comment]
I updated the manifests for the themes. I've also tagged beta pre-releases at each of their respective repos for history/posterity.
