### ISSUE TITLE
[meta] Textpattern 4.7.0 pre-launch snagging

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1257]
Please list below any blocking issues to the release of Textpattern 4.7.0.

- [x] https://github.com/textpattern/textpattern/milestone/2
- [x] document pre-4.2.0 upgrade requirements (https://github.com/textpattern/textpattern/issues/1242#issuecomment-387890630 & https://github.com/textpattern/textpattern/issues/1242#issuecomment-385668626)
  - [x] `HISTORY` (https://github.com/textpattern/textpattern/pull/1258)
  - [x]  `README` (https://github.com/textpattern/textpattern/pull/1259)
  - [x] docs site (https://github.com/textpattern/textpattern.github.io/commit/3712430ec1e4329c668a8e78878f2f70afbb5ba0)
  - [x] forum (https://forum.textpattern.io/viewtopic.php?id=48695)
  - [x] ~~blog post~~ (not a blocker, can be done in release announcement)
- [x] standardise on (PHP) system requirements (https://github.com/textpattern/textpattern/issues/1263)
  - [x] pophelp (https://github.com/textpattern/pophelp/commit/fc7abf0e95679b71b729a07385b2011658c1f996)
  - [x] code (https://github.com/textpattern/textpattern/commit/e2f88f5637c1a5ee1e9faed7ff0f5649db8a260b)
  - [x] ~~docs site~~ (not applicable)

**Comment by petecooper** [comment]
All clear!
