### ISSUE TITLE
Snagging list for 4.7.2

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1352]
Just a collection of 4.7.2-related things to do. Add/tick off as you see fit, anyone:

* [ ] [New text strings](https://github.com/textpattern/textpattern/issues/1349)
* [ ] [Aria-label placeholder attributes](https://github.com/textpattern/textpattern/issues/1351)
* [ ] [New form types](https://github.com/textpattern/textpattern/issues/1299) (mostly done)
* [ ] [Removing unused Textpack strings](https://github.com/textpattern/textpattern/issues/1039)
* [ ] [on/off radio styling](https://github.com/textpattern/textpattern/issues/1235) [stef, probably]
* [ ] [Theme workflow enhancements](https://github.com/textpattern/textpattern/issues/1196) (mostly addressed?)
* [x] [Assets panel instead of styles](https://github.com/textpattern/textpattern/issues/1248) (Can be closed, right?)

Can anyone see a reason why the current dev branch can't be merged into 4.7.2? There are no conflicts but I don't want to do it in case there's any 4.8-work gone into dev and we need to therefore cherry pick. Anyone?

**Comment by philwareham** [comment]
I haven't done any work specifically for 4.8 yet. Waiting for 4.7.2 to drop first. I don't think anyone has done stuff yet that can't be merged in 4.7.2 branch. Just need to make sure version numbers are OK (the README.md seems to be the only place 4.8 is mentioned, so we'd need to edit that).

For the assets panel, does that need new Textpack strings too?

**Comment by Bloke** [comment]
Cool, we can worry about the README after merge.

> For the assets panel, does that need new Textpack strings too?

I think both Styles and Forms need a new string to cater for the 'Export to disk' checkbox (that's `admin-side`) plus there's the new pref but the dust is still settling there. Think that's it.

**Comment by bloatware** [comment]
I think [Themes workflow](https://github.com/textpattern/textpattern/issues/1196) issue is not exactly solved. It is about flat development mode, not about flat themes storage/output that we have enhanced recently. There is a working plugin prototype, but it lacks features like automatic fs->db sync hook and perhaps more. Not sure this should be included in 4.7.2 core, but if someone has time to finish it, please do.

**Comment by bloatware** [comment]
Only #1364 and #1370 seem to be release blockers, plus docs update. I can take #1370 if it helps @Bloke with #1364 fix.

**Comment by Bloke** [comment]
By all means take #1370 @bloatware. I'll try and tackle 1364 tonight when I get back from my cup match.

**Comment by philwareham** [comment]
Cheers guys, yes the other items on list can wait until 4.8 I think. There was another issue that I don’t know what it is or if important https://github.com/textpattern/textpattern/issues/1328

Other than that, let’s get this thing out and have a relaxing Christmas break 😀

**Comment by bloatware** [comment]
@Bloke so, the match..? :-)

**Comment by Bloke** [comment]
Got hammered 5-0! :(

But they're in the division above us and we put up a fight - the first three sets went to five games so it could have gone either way. Table tennis is a funstrating sport at times!

**Comment by philwareham** [comment]
So, are we just about ready to go for 4.7.2 release? There is the issue of Textile non-official release (3.7 dev build) in our codebase. I could simply do a release of Textile as I have commit rights but I don't want to trample on anyone's release plans (but I do want to release Textpattern obviously).

**Comment by petecooper** [comment]
@philwareham Are you thinking beta release first?

**Comment by philwareham** [comment]
Since it's a minor point release, no - just a final release. Although I agree it has had a few feature additions so is technically not a minor point release - but hey, that's Textpattern (bear in mind we have never had a major point release in over 15 years, as the first shipping version was 4.x - ha ha!).

I would prefer to move on to v4.8 work n the New Year - this dev cycle has had a fair amount of user testing I feel anyway.

**Comment by Bloke** [comment]
I'm tempted to just go for it. I have 4.7.2-dev running on at least one live site without issue. My only concern besides Textile is that non-opening of old "illegal" Form names. Would like to ideally fix that asap, in one way or another but it's proving tricky. Guess we can live with it and just document  the behaviour. It should be documented anyway.

**Comment by philwareham** [comment]
> I'm tempted to just go for it.

You mean release Textile. You are the owner of that project now so it's your call ;)

**Comment by petecooper** [comment]
>My only concern besides Textile is that non-opening of old "illegal" Form names. Would like to ideally fix that asap, in one way or another but it's proving tricky.

As the reporter of that issue (https://github.com/textpattern/textpattern/issues/1329 for completeness) I only discovered it when migrating textpattern.org to the new server, and it's not clear to me how long it's been an issue. Was it introduced in 4.7.0 or earlier?

**Comment by petecooper** [comment]
>Guess we can live with it and just document the behaviour. It should be documented anyway.

Welcome aboard https://github.com/textpattern/textpattern.github.io/issues/117

**Comment by Bloke** [comment]
I meant go for a full 4.7.2 without beta. Textile seems stable enough but whether we wait a day or so to see if gocom replies then decide if we want to release Txp with beta textile or release textile as-is first.

**Comment by Bloke** [comment]
As for the illegal form names I'm pretty sure it was like that in 4.7.0.

**Comment by philwareham** [comment]
Ok Julka has releases Textile 3.7 so I’ll roll that in Monday and then we can release I believe. If anyone wants to draft a blog article then please do otherwise I’ll give it a try Monday too. Maybe aim for Tuesday release?
