### ISSUE TITLE
Textpattern 4.8.0 beta release - preflight

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1431]
We are targeting Textpattern 4.8.0 for release in Q1 2020.

Please update this post and subsequent replies with tasks etc as needed, assigning yourself or others where appropriate.

**Schedule**
- [ ] agree release schedule (beta # -> RC # -> GA), with dates (all)

**Core**
Issue milestone for 4.8: https://github.com/textpattern/textpattern/milestone/4
- [x] remove `register_globals` and `safe_mode` references (https://github.com/textpattern/textpattern/issues/1086)
- [x] sanity check 4.9 milestone for 4.8 stragglers (https://github.com/textpattern/textpattern/issues/1431#issuecomment-559492729)

**Textpacks**
Issue milestone for 4.8: https://github.com/textpattern/textpacks/milestone/3
- [x] latest translations from CrowdIn (@philwareham)
- [x] add `section_category_title` and `breadcrumb_title` permlink modes strings (part of https://github.com/textpattern/textpacks/issues/283) (@philwareham)
- [x] move all permlink modes strings to admin-side section (@philwareham)

**Pophelp**
Issue milestone for 4.8: https://github.com/textpattern/pophelp/milestone/3

**Docs**
Issue milestone for 4.8: https://github.com/textpattern/textpattern.github.io/milestone/2
- [x] change any references to latest version to be 4.8.0, if any remain (@wion)

**Testing**
- [x] reconfigure `beta-demo` to use PHP 7.4 after beta.1 (@petecooper)
- [x] reconfigure `beta-demo` to point at 4.8 pre-release(s) after beta.1 (@petecooper)

**PR**
- [x] announcement blog posts (@Bloke and/or @petecooper)
- [x] announcement on Twitter (@petecooper since it's Saturday)

**Comment by petecooper** [comment]
I've done a first pass on the 4.8 milestone and deferred a bunch to 4.9, removing milestones from a few others since they've drifted too far. To that end, the majority of open issues with a milestone are now attached to the 4.9 release: 

So, flipping the sort logic around, please take a few minutes to sanity check the 4.9 milestone to see if there are any addressable in 4.8 as easy wins, and re-target ar 4.8. Paging @bloatware @Bloke @philwareham - please tag a thumbs up when you're happy the 4.9 list is broadly correct. Thank you.

https://github.com/textpattern/textpattern/milestone/5

**Comment by Bloke** [comment]
@bloatware Should the 'View' link on the Write panel and the 'Live' links in the Status column on the Articles panel respect the per-section permlink that's set? I suppose it makes it tricky - at least on the Write panel - because changing Section and Saving the article needs to update the View link.

Is this one of those times when we say it's only a feature from the front side? Or can the admin-side also play?

**Comment by bloatware** [comment]
@Bloke good catch, thanks. Should be fixed now.

**Comment by wion** [comment]
> Docs . . . change references to latest version to be 4.8.0

Just need a little more context, please.

Is this suggesting I find all instances of '4.7.x' in docs and change them to '4.8.0'?  If so, I wouldn't know where to start. But it does make me think of a couple things:

1. If there's not already an include for quick-changing version numbers peppered around docs, then that's something to think about setting up and editing in where numbers exist, as they are found.
2. Ideally, docs are not written with a bunch references to specific numbers, for this very reason; it becomes a lost cause without a universal include or something to manage it. Better to just rephrase things so no version numbers are used at all and/or give a link to some resource that can speak to what is current and timely (e.g. 'the [latest release](https://textpattern.com/start)', or 'in the [current version](https://textpattern.com/start)').

Or did I completely misunderstand what I'm tasked with? Probably.

**Comment by petecooper** [comment]
>Or did I completely misunderstand what I'm tasked with? Probably.

Nope. Broadly, I recall seeing references to 'the current version of Textpattern is x.y.z', but this was >1 year ago, so they have been massaged out. This task was purely a docs search for any statements like the above that infer an old(er) version is current. May well be a two minute task, especially if you're actively combing docs at the moment and you're not aware of any references.

On your points:

1. Agreed. Might be tricky within the confines of GitHub Pages, especially if we're including a file with a version/variable.
2. Agreed. As I say, there _were_ references to version numbers in the past, it's entirely plausible most or all have been scrubbed over time.

**Comment by wion** [comment]
Cool. It's a great point and definitely something to watch for. I'll issue it in docs repo for the long haul (checklist any found pages), possibility for automating, and add the relevant writing guideline to the relevant style guide. That's probably the best way to check my box here.

**Comment by Bloke** [comment]
The only places we should mention the version is on the tags pages where we say things like 'updated in x.y.z' or the genealogy section.

Here's the current [list of references to 4.x](https://github.com/textpattern/textpattern.github.io/search?q=v4.7&unscoped_q=v4.7). Only found a handful besides tags:

* https://github.com/textpattern/textpattern.github.io/blob/b1d8d0482643fcbd7eb90050d71e5c6c7339bcce/themes/themes-on-github.md
* https://github.com/textpattern/textpattern.github.io/blob/a812debddd44c4d407499e468a27de473c0e3724/administration/index.md
* https://github.com/textpattern/textpattern.github.io/blob/615089c913289dcf1d5466d6990678e5b6ab19f5/administration/preferences-panel.md
* https://github.com/textpattern/textpattern.github.io/blob/cf35234ff354adb2397c9d9002afac466b6b3fbd/brand/user-docs-guide.md

**Comment by wion** [comment]
Yeah, legacy mentions are fine. I think it's only a problem where talking about current functionality.

https://github.com/textpattern/textpattern.github.io/issues/123#issuecomment-559940104

**Comment by wion** [comment]
@bloke, do you have some sneaky way of bulk searching the tree? When I do a search using the _huge_ search box on the docs main page for 'version 4.7' or just '4.7', I get zip.

**Comment by petecooper** [comment]
@wion - use GitHub search instead, much better. Or clone repo to your local computer and search with your IDE (try Atom - https://atom.io - it's free and capable).

**Comment by Bloke** [comment]
The search is a bit pants, yes. Searching for numbers returned nothing, searching for 'v4.' worked. *shrug*

**Comment by wion** [comment]
Yeah, I have it local. I'll look into that.

Maybe this means fixing the user docs search? A broken search on user docs is a bit ironic. Or, hook it up to a GitHub search? Would that be possible? Maybe that needs an 'architecture' issue?

**Comment by Bloke** [comment]
I meant the search box at the top of the panel in GitHub. The one that allows you to search within a repo.

**Comment by wion** [comment]
Right, but if the one on front-side main-page of docs is pants, the one I used with sad success, shouldn't that get some attention?

I just tried it again using 'sections' , 'sections panel', and 'administration'. No results on any of them. There's a problem there.

**Comment by wion** [comment]
I'll ticket it in docs repo.

**Comment by philwareham** [comment]
I'm ready to go to beta release. Nothing left to add from my site for now. Have a good Christmas!

**Comment by petecooper** [comment]
@Bloke @bloatware - are you OK to proceed to beta?

**Comment by Bloke** [comment]
Can't see any impediment.

Just need to figure out what to do with the upgrade script. When set as _to_4.8.0.php it doesn't run if the version string is set to 4.8.0-beta, so I presume we'll need to rename it and then change the name again when we move to 4.8.0 final. Can't remember what we normally do, I'll have to look in the archives to find out.

It'd be nice if we didn't have to do this little dance and the upgrade script figured out that 4.8.0-dev needed to actually call the _to_4.8.0.php file. Maybe we should strip off the suffix when comparing file and version names?

**Comment by petecooper** [comment]
>I'll have to look in the archives to find out.

Is this any help?:

https://github.com/textpattern-community/textpattern-releases

**Comment by Bloke** [comment]
Yeah. But I think we've tweaked the upgrade script in recent times and, for reasons I can't recall, the `version_compare()` seems to not take the suffix into account, or it's ignoring the `$txp_is_dev` (which is still set for betas). PHP does compare correctly but our internal comparison - either to the table or the files, I'm not sure which - fails.

Let me just get my head straight after watching Episode IX and I'll look into it :)

**Comment by petecooper** [comment]
>Let me just get my head straight after watching Episode IX and I'll look into it :)

I'll be around if you need extra brainz.

**Comment by Bloke** [comment]
> I'll be around if you need extra brainz.

Thank you. *tries not to write __Mmmm, Daisy Ridley__ in update script*

**Comment by Bloke** [comment]
Okay, release prepped. Files, uploaded to .com, blog post cobbled together - please verify it's okay and push the button when any other assets such as demo site are available. Do we assign the 'current' categories to the beta files? Can't remember.

Thank you all, especially for the last few weeks of back and forth with bug sleuthing and feature finalising! You're all awesome.

**Comment by petecooper** [comment]
`beta-demo` online and serving `4.8.0-beta`:

![Screenshot 2019-12-21 at 15 46 24](https://user-images.githubusercontent.com/226578/71310195-358d9c00-2409-11ea-8264-3cdac230625e.png)

**Comment by bloatware** [comment]
@petecooper some CSP settings o check?

**Comment by petecooper** [comment]
@Bloke - couple of changes in blog post made (evolution -> iteration) and I've linked DO with the preferred UTM stuff.

**Comment by petecooper** [comment]
@bloatware - can you post details of the error(s) you're seeing?

**Comment by Bloke** [comment]
Nice one, thanks Pete. I just cloned the old 4.7.0 blog post, edited it a bit and then had to run out so didn't get time to proof it properly. Any improvements welcome.

**Comment by bloatware** [comment]
@petecooper Article edit sidebar is loaded unfolded and not collapsible via `Collapse all` on the first click.
Got
```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« style-src »).
```

**Comment by petecooper** [comment]
@bloatware I think this is fixed now - please test.

**Comment by bloatware** [comment]
@petecooper much better :-)

**Comment by petecooper** [comment]
@Bloke I'll double check text again now that inline CSS is sorted, happy for me to make it live or do you want final cut?

**Comment by Bloke** [comment]
Go for it whenever you think it's consumption-ready.

**Comment by petecooper** [comment]
Article goes live 1630UTC, couple more changes made - please hack and change as needed.

**Comment by petecooper** [comment]
@Bloke - can you post a forum thingy so I can link to the feedback thread on the Twitter announcement, please and thanks?

**Comment by Bloke** [comment]
[Done](https://forum.textpattern.com/viewtopic.php?id=50516)

**Comment by petecooper** [comment]
Closing this issue now, will start a fresh one now 4.8.0-beta is out. Thank you all for your invaluable commentary, assistance and work.
