### ISSUE TITLE
Textpattern 4.8.3 release flight plan

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1534]
We are targeting Textpattern 4.8.3 for release in September 2020.

* [4.8.3 branch](https://github.com/textpattern/textpattern/tree/4.8.3)

Please update this post and subsequent replies with tasks etc as needed, assigning yourself or others where appropriate.

## Preflight

**Repo Issues**

* [`textpattern/textpattern`](https://github.com/textpattern/textpattern/milestone/16)
* [`textpattern/textpacks`](https://github.com/textpattern/textpacks/milestone/7)
* [`textpattern/textpattern.github.io`](https://github.com/textpattern/textpattern.github.io/milestone/2)
- [x] Merge 151d697d bug fix in from dev.
- [x] latest translations (@philwareham)
- [x] latest pophelp (@philwareham)
- [x] draft .com blog post (@petecooper) 
- [x] update .com draft blog post with shiny newness (@petecooper) 

## Take Off

- [x] package up for GitHub and .com (@Bloke)
- [x] update demo site (@petecooper)
- [x] publish .com blog post (anyone)
- [x] forum announcement (@petecooper)
- [x] forum feedback (@petecooper)
- [x] socials (@petecooper)
- [x] tag public/admin themes with release tag (@philwareham)
- [x] tag Textpacks and Pophelps with release tag (@philwareham)

### Toolbelt step progress

- [x] Step 0: Ensure everything is up-to-date
- [x] Step 1: Create release branch based on feature branch
- [x] Step 2: Update history
- [x] Step 3: Set version numbers for all but `textpattern/index.php`
- [x] Step 4: Ensure Unix line endings
- [x] Step 5: Verify setup/update scripts match
- [x] Step 6: Commit history and versions
- [x] Step 7: Bump official version
- [x] Step 8: Update checksums
- [x] Step 9: Test!
- [x] Step 10: Merge to the main repo
- [x] Step 11: Build the archives
- [x] Step 12: Verify archives
- [x] Step 13: Build release on GitHub
- [x] Step 14: Add archives to textpattern.com
- [x] Step 15: Adjust archive category assignment
- [x] Step 16: Finalise the release blog article
- [x] Step 17: Update orientation information
- [x] Step 18: Prepare for next version
- [x] Step 19: Set version numbers for next version
- [x] Step 20: Set `dev` and commit next version
- [x] Step 21: Merge release back into dev
- [x] Step 22: Tidy up branches
- [x] Step 23: Tell everyone
- [x] Step 24: Update links to latest version in docs, etc
- [ ] Step 25: Relax

**Comment by petecooper** [comment]
I'll start on the release blog post now.

**Comment by petecooper** [comment]
@bloatware - I'm a bit fuzzy on the fix that's the priority in this release, when you have a moment could you please raise an issue so we can track it here? Thank you.

**Comment by bloatware** [comment]
@petecooper [done](https://github.com/textpattern/textpattern/issues/1535), feeling bureaucratic :-)

**Comment by Bloke** [comment]
I would say we should pull 151d697d into 4.8.3 as well, since it's a holdover bug that I've now had three attempts at fixing and _still_ isn't right in 4.8.2. Hopefully this is the last of it and all panels behave properly under both 'no results' search conditions and 'no assets recorded' conditions. If you get a chance to test the correct messages are displayed on all panels with/without assets and with/without matching search results and pagination, please do.

I kept the commit atomic on purpose so it _should_ cherry pick cleanly into 4.8.3 now it's merged into dev from the csp branch. I'll add it to the list above and anyone who has a chance to pull it in, by all means. If not, I'll do it later.

**Comment by petecooper** [comment]
Good day, sirs. I've been away and offline for 5 days, it was fantastic and terrifying. Now I'm back, which is also fantastic and terrifying.

How are we looking for a 4.8.3 release this week?

@Bloke - did https://github.com/textpattern/textpattern/commit/151d697d5c16180252830978b117a365059f71ec get merged in yet? I can take a look tomorrow (with the obligatory fresh eyes) and do it piecemeal if not.

**Comment by Bloke** [comment]
It is now, thanks for the nudge.

**Comment by philwareham** [comment]
There is issue #1538 that might need attention. Basically we should ensure that styles can’t be entirely deleted (there should always be at least one).

**Comment by bloatware** [comment]
+1 for #1538, though my first attempts have been a failure.

**Comment by petecooper** [comment]
Speculative question about 4.8.3 - how urgent and important is it? I get the feeling I'm misunderstanding the extent of https://github.com/textpattern/textpattern/issues/1538, so please excuse any unintended ignorance.

It appears that a tentative fix is in place (thank you @bloatware), and that we need to resolve a sub-issue (?) outlined here: https://github.com/textpattern/textpattern/issues/1538#issuecomment-678280185

Obviously it's totally OK if this takes time to process, getting it done correctly is more important than getting it done quickly, but I'd really appreciate some guidance on how close we are to release, please and thanks.

**Comment by philwareham** [comment]
I’m in holiday this week, so can’t test, but as long as the import/export of themes works regardless of if styles are present - that is good enough for now.

**Comment by bloatware** [comment]
For me, the main raison d'être of 4.8.3 was a bug breaking old-style public-side plugins. Put shortly, plugins tags output `1` instead of nothing under some circumstances. The effect can be just cosmetic or quite annoying depending on how the tag is used. I wouldn't like to take the risk of site breakage on 4.8.2 updates after summer holidays and nothing in #1538 seems to justify it.

**Comment by philwareham** [comment]
Ok
Let’s just release as is.

**Comment by bloatware** [comment]
There is a slight discrepancy when importing a theme with sync: if `styles` subdirectory exists but is empty, all styles are removed from db as expected. But if the disk version does not contain `styles` subdirectory at all, no style is removed from db (we actually even don't call `import()` function for `styles`). I kind of know how to patch it, but am not sure it is not intentional.

**Comment by petecooper** [comment]
@Bloke - what's your take, please? Go or No-Go from your side?

**Comment by petecooper** [comment]
Given that we're in September and PHP 8.0.0 is due out by the end of November, do we need to consider another patch release after 4.8.3? Or do we delay 4.8.3 until we're sure it's working with PHP 8? Or feature freeze 4.8 and *just* patch the bits needed to make it work with PHP 8.0.0? Or something else?

Current schedule for PHP 8 https://wiki.php.net/todo/php80

**Comment by bloatware** [comment]
I wouldn't like to delay 4.8.3, the plugin-breaking bug is annoying. If necessary, 4.8.4 is ok for me.

**Comment by philwareham** [comment]
Let's release it. I'll add any latest translations today.

**Comment by bloatware** [comment]
It can wait few days if @Bloke has time to patch [this](https://forum.textpattern.com/viewtopic.php?pid=325569#p325569). I'm always anxious when touching this part of core.

**Comment by petecooper** [comment]
Much obliged, sirs. +1 on all the above.

**Comment by Bloke** [comment]
I'll see what I can do about that theme issue when I get back off hols. Cruddy (no) WiFi here in the rooms, and communal spaces where there _is_ coverage are shut. In the meantime, if anyone wants a crack at it, be my guest.

**Comment by bloatware** [comment]
May be [fixed](https://github.com/textpattern/textpattern/commit/36b0686408298e69824a376bda0d56d035c1cdfd), may be not..

**Comment by petecooper** [comment]
>May be fixed, may be not..

I'm inclined to say it's fixed, given Phillipe's positive feedback and thoroughness with which he tests this stuff.

**Comment by Bloke** [comment]
Thank you, @bloatware . Your fix was far more eloquent than anything I'd have come up with.

**Comment by Bloke** [comment]
@bloatware Any side-effects of [doing this](https://github.com/textpattern/textpattern/commit/a5bd5b4a825d94011534f565964bce3a6dffb818) and do we need to also order them when they're pulled out in textpattern/publish.php? I'm not entirely sure under what circumstances txp_sections is used in the publish path vs the index path. Presumably to save a query when dealing with taghandlers?

If sorting them by `title,name` at that point is not a good idea (does it affect theme code?) we can always do it locally in txp_article by doing a `ksort()` or something like that.

**Comment by bloatware** [comment]
@Bloke I don't see any side-effects, on neither public nor admin side, feel free to modify it. On the public side it saves few queries (like filter by `on_frontpage`, `searchable` etc) but the order is not important. Since some functions using `$txp_sections` are called on both public and admin sides, it is defined in `textpattern/index.php` too.

**Comment by Bloke** [comment]
If the order's not important on the public side, we can leave the one in publish.php as-is.

**Comment by bloatware** [comment]
@Bloke the only public place I can see where order is important is `<txp:section_list />` tag, but it is set by `sort` attribute. We could do a `ksort()` to spare a db query, but conjunctively with `limit`, `offset` etc it becomes complicated. So yes, leave it as is for me.

**Comment by philwareham** [comment]
As far as I'm concerned - 4.8.3 can release whenever you are ready. Cheers all.

**Comment by bloatware** [comment]
Should we add #1545 (basic version) for completeness?

**Comment by philwareham** [comment]
Yes please, if we can! Always nice to have a couple of new features. 😀

**Comment by petecooper** [comment]
![IMG_7641](https://user-images.githubusercontent.com/226578/92781389-00144e80-f39c-11ea-903d-15124ce618d7.jpg)

I've been saving this…

**Comment by bloatware** [comment]
A bit of [testing](https://github.com/textpattern/textpattern/commit/313cdd1c32d832e2771115b2d8bed244753041d0) and go for me.

**Comment by philwareham** [comment]
> A bit of testing and go for me.

Tested and happy to go!

**Comment by philwareham** [comment]
OK, I have tagged the themes, help files, textpacks with `4.8.3`. Over to you guys for release. Have a good weekend!

**Comment by Bloke** [comment]
Woop woop! Thanks everyone. I'll do a little testing this afternoon and bundle everything up tonight.

**Comment by bloatware** [comment]
@Bloke image tags would benefit from some code modernisation, but I had no courage... up to you.

**Comment by Bloke** [comment]
Image tags: another day, another version. They'll need changing anyway when we add multi thumb support and possibly srcset/picture support so that's an ideal time to overhaul them.

**Comment by bloatware** [comment]
> another day, another version

I adhere

**Comment by petecooper** [comment]
I'll update draft .com post this evening, I'm probably more use tomorrow AM than tonight realistically, but please ping me if you need extra eyes tonight @Bloke.

**Comment by Bloke** [comment]
@petecooper Thank you. I can defer release till the morning, no worries.

**Comment by petecooper** [comment]
@Bloke - no, crack on - I'm an early bird these days, I'll take the day shift. If you can get the good stuff bundled I can handle the admin with fresh eyes tomorrow. Doable?

**Comment by Bloke** [comment]
Aye.

**Comment by petecooper** [comment]
OK, release blog post tweaked and now up-to-date, 431 ready for more eyes. @Bloke - I'll make it live tomorrow if it ends up being a late night for you, I haven't yet updated demo sites so perhaps comment that line out if you do flip the switch.

**Comment by Bloke** [comment]
Slight anyag.

My Mac just died on me. MacOS started throwing random errors like "such and such unexpectedly quit" then the thing just powered down and now it kernel panics every time I try and boot. Think the SSD has just expired without warning. Grrr.

Tried usual recovery stuff (nvram/pram/smc reset) and taking the thing apart to check for loose connections but nothing's worked so far :(

The drive partitions are _detected_ on Windows so the drive is functioning if I put it in a USB caddy, but for some reason MacOS can't select it as a system disk nor restore to it. It's just not there in the list so maybe the EFI/GPT is mashed or something. Might try and initialize the drive somehow from Linux/VirtualBox or something.

Anyway, I've located an old spinning 2.5" drive and installed it. Just waiting for Time Machine to do a restore from a backup I made a couple of weeks ago before I jumped to Mojave. All my data is on a second internal disk so that should be safe. Just hoping Mojave didn't rewrite file descriptors for APFS or all my files'll be inaccessible from Sierra until I reinstall Mojave.

Assuming it is just the disk that's bust, when the new one arrives I'll maybe fresh build Mojave on it and recreate the symlinks to my second drive.

Anyway, all that's to say the Txp build process is halted right now. By all means, if someone else wants to do it, be my guest.

I did spot a few oddities last night with empty /css dirs when importing from disk. Like, if you delete `default` in the DB and sync export, the disk /css gets wiped, as expected. But if you recreate it and add a non-css files (e.g. .scss) or a file that's _not_ default.css and then sync import, you get `default` created in the DB with an empty placeholder comment. But under other conditions I haven't nailed down yet, the default entry isn't created in the DB.

Not a show stopper. Just a little odd. I was in the process of testing it when my drive died. If anyone can replicate such findings, please report. Might just be me missing something obvious.

**Comment by phiw13** [comment]
> I did spot a few oddities last night with empty /css dirs when importing from disk. Like, if you delete default in the DB and sync export, the disk /css gets wiped, as expected. But if you recreate it and add a non-css files (e.g. .scss) or a file that's not default.css and then sync import, you get default created in the DB with an empty placeholder comment. But under other conditions I haven't nailed down yet, the default entry isn't created in the DB.

Yes, I mentioned that creating of a `default.css` at import time in my forum comment. Yesterday i noticed some other oddity on my test site. The `theme-in-use` had originality no stylesheet registered / available in the DB. A few days after doing all that testing, I added back a `test.css` file which I use at times for debugging purposes. To my surprise yesterday, there was also a `default.css` in there. I had not synced with disk versions or whatever. The only thing that might have change is that I quit and restarted Safari on the  way, which forced me to log in again. I not have had time / energy to investigate more.

me thinks that if a `default.css` must exist, then it should not be possible to delete it.

–^–^–

ps - good luck with the SSD. I have not yet had the opportunity to “enjoy” that situation but others have told me about the nuisance of those things dying without warning.

**Comment by petecooper** [comment]
I'll start the build and release process this afternoon - please refrain from any further changes from now until I give the all clear.

I've had a good look through the release process docs and I'll take it step by step. This will be a good exercise to battle test the release docs, and I'm sure it's not as terrifying as I think it is.

Thank you for your patience. I will post a follow up comment with checkbox status for each step. Someone have the brandy ready at the end, please and thanks.

**Comment by petecooper** [comment]
It looks like `4.8.3` is two commits ahead of `dev` - there's a README credit and some image loading voodoo on the diff:

https://github.com/textpattern/textpattern/compare/4.8.3

Could someone with the appropriate pay grade please take a look merge if appropriate, please? Thank you.

**Comment by Bloke** [comment]
Doesn't matter if 4.8.3 is ahead because that's the branch you're basing the release-4.8.3 on. When you get to the place where you remerge release-4.8.3 back into dev, the extra two commits will come along for the ride.

**Comment by petecooper** [comment]
OK, cool - today I learned. Thanks @Bloke

**Comment by petecooper** [comment]
Started release process. OP updated with steps progress.

**Comment by petecooper** [comment]
@Bloke - regarding next version (step 17) - you want `4.8.4-dev` or `4.9.0-dev`, please?

**Comment by Bloke** [comment]
Just go with 4.9.0-dev. No point busting off a 4.8.4 unless we need it.

**Comment by petecooper** [comment]
>unless we need it.

I had https://github.com/textpattern/textpattern/issues/1546 in mind.

**Comment by Bloke** [comment]
Aye, but in terms of immediate steps, if you try and merge release-4.8.3 back into dev in a few steps' time with 4.8.4-dev in it, you'll get merge conflicts and will have to fix them before you can commit. It's cleaner to pretend we're going straight to the next minor release after each feature branch to just make merges simpler, then break off a new feature branch or 4.8.4 _from main_ so the tree stays intact.

**Comment by petecooper** [comment]
https://textpattern.com/weblog/431/textpattern-cms-483-released

https://forum.textpattern.com/viewtopic.php?id=51058 (feedback)

**Comment by petecooper** [comment]
Demo site running 4.8.3 just fine, no checksum errors, no diagnostic weirdness. I think that's it.

I have renamed `4.8.3` to something more obvious on the off chance we need to pick anything from it. If you're happy it's done, please zap that branch.

All that's left is the docs checks, I'll need fresh eyes for that cos it's been a full-on few hours and I need some fresh air!

**Comment by Bloke** [comment]
Nice one, Mr Cooper. Any amendments needed to the toolbelt docs for clarity?

**Comment by petecooper** [comment]
Yep, a few minor points and tightening up - frankly I'm so exhausted they'll have to wait until after I've had a break!

A lot of the build process can be automated to a greater extent, so there's definite value in building out a shell script to make it less arduous.

**Comment by Bloke** [comment]
I'm down with automation. Just not so keen on automating the git bits as there's lots of potential to blow up. But yeah, the bundling and packaging could even be rsynced

**Comment by petecooper** [comment]
Definitely not the git parts, fully agreed.

**Comment by petecooper** [comment]
Closing for now. I have a few notes on the release process that I'll look into and perhaps raise as issues - nothing major.

Thanks everyone, a distinct pleasure working alongside you - you've raised the bar once again.

**Comment by Bloke** [comment]
Nice one @petecooper . Thanks so much for taking the release process for a spin. Anything we can automate in future to cut down on steps is great!
