### ISSUE TITLE
Textpattern 4.8.4 release flight plan

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1565]
We are targeting Textpattern 4.8.4 for release in late November 2020, around the time of the GA release of PHP 8.0.0. At the time of writing, this is [expected](https://wiki.php.net/todo/php80) to be 26 November 2020.

* [4.8.4 branch](https://github.com/textpattern/textpattern/tree/4.8.4)

Please update this post and subsequent replies with tasks etc as needed, assigning yourself or others where appropriate.

**Repo Issues**

* [`textpattern/textpattern`](https://github.com/textpattern/textpattern/milestone/17)
* [`textpattern/textpattern.github.io`](https://github.com/textpattern/textpattern.github.io/milestone/2)

## Preflight

- [x] latest translations (@philwareham)
- [x] latest pophelp (@philwareham)
- [x] draft .com blog post (@petecooper)
- [x] write change history (everyone)

## Take Off

- [x] package up for GitHub and .com (@Bloke)
- [x] update demo site (@petecooper)
- [x] publish .com blog post (anyone)
- [x] forum announcement (@petecooper)
- [x] forum feedback (@petecooper)
- [x] socials (@petecooper)
- [x] tag public/admin themes with release tag (@philwareham)
- [x] tag Textpacks and Pophelps with release tag (@philwareham)

## Misc

- [x] re-pin https://github.com/textpattern/textpattern/issues/968

**Comment by petecooper** [comment]
@Bloke @bloatware @philwareham – if you have patches to get into 4.8.4, please raise an issue for each in the appropriate repo(s) so we can track their progress. Thank you!

**Comment by petecooper** [comment]
I'll start on the .com article this weekend.

**Comment by petecooper** [comment]
Blog post drafted - have a peep at 432 if you're curious, I'll tweak as we get closer to launch.

**Comment by philwareham** [comment]
Latest translations are into the repo - so apart from tagging various theme/languages releases, my part is done and ready for release.

**Comment by petecooper** [comment]
Expecting PHP 8.0.0 GA to land tomorrow (Tuesday), and @Bloke is kindly attending to https://github.com/textpattern/textpattern/issues/1567 so I think that clears all preflight checks barring any late-breaking snags with tomorrow's GA.

I will post here when the dev demo is updated, and we'll need a commnunity call to action to test it out, but I think beyond that we're ready and we've done all we can do.

Any objections for a Thursday / Friday release if we're smooth sailing with PHP 8.0 GA?

**Comment by philwareham** [comment]
> Any objections for a Thursday / Friday release if we're smooth sailing with PHP 8.0 GA?

Fine by me. If any further translations happen between now and then I'll squeeze them in.

**Comment by philwareham** [comment]
I've tagged the various themes with the 4.8.4 release number now. Will do the Textpacks/Pophelps just before we plan to release, to catch any last minute translations. Go when you are ready and happy to.

**Comment by petecooper** [comment]
I'm expecting PHP 8.0.0 to land any time, from the commits it looks like bug fixes from RC5 to GA, so should be smooth sailing.

**Comment by philwareham** [comment]
Can you all please fill out any history for changes made in 4.8.4, when you get a spare moment. It's a bit empty right now and there are definitely changes in 4.8.4 that are not listed yet. Cheers!

**Comment by petecooper** [comment]
I've done a few that I understand, and made the headline change support for PHP 8.0, so we can ~~blame them~~ use that as a the primary reason.

**Comment by petecooper** [comment]
Hold off on releasing for a bit – found a possible user privileges issue that I need to dig into.

**Comment by petecooper** [comment]
**GO or NO GO on `4.8.4` branch to be released as Textpattern 4.8.4.**

PHP 8 support seems sound, I have not yet found any issues. There aren't swathes of changes since 4.8.3, and psychologically we can benefit from a single `dev` branch for the next phase of focus if we're broadly happy with how 4.8 has shaped up.

@bloatware @Bloke @philwareham – please thumbs up or down at your convenience.

Thank you.

**Comment by philwareham** [comment]
Go from me

**Comment by petecooper** [comment]
Possibly relevant commits that might need documenting (sadly beyond my current comprehension)…

Cunning etcVoodoo™:

- [ ] https://github.com/textpattern/textpattern/commit/20afaa5f0b905570dac14d7c21d277b782d9ef4a
- [ ] https://github.com/textpattern/textpattern/commit/fe60a836d934d9f3d8c4f760f9c46754d9b93a9e
- [ ] https://github.com/textpattern/textpattern/commit/38ba55c0733accc4924bccbea388f1a9054a5721
- [ ] https://github.com/textpattern/textpattern/commit/5d05861f68e1dbc17961d973d1744a88c1a3ecb8

Article form override stuff:

- [ ] https://github.com/textpattern/textpattern/commit/0ab56200333e625d09160e2bb0808f3fd349f2e8
- [ ] https://github.com/textpattern/textpattern/commit/aa49ab734b759e5b1f05c93feaad5c87b1e0fdb1

**Comment by petecooper** [comment]
Commencing release process. Please stand by.

**Comment by petecooper** [comment]
https://textpattern.com/weblog/432/textpattern-cms-484-released-php-80-compatible

**Comment by petecooper** [comment]
I haven't yet nuked `4.8.4` – release is done, but I need additional eyes to make sure I didn't miss anything.

**Comment by petecooper** [comment]
OK, I think it's safe to zap `4.8.4` now - any objections, please speak now, otherwise I'll cull at 1800UTC today.
