### ISSUE TITLE
Textpattern 4.8.8 release flight plan

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1720]
We are targeting Textpattern 4.8.8 for release in Q4 2021 to provide initial support for PHP 8.1, address some snags, and provide further refinements. The release flight plan includes at least one beta release before the production release.

* [4.8.8 branch](https://github.com/textpattern/textpattern/tree/v4.8.8)

Please update this post and subsequent replies with tasks etc as needed, assigning yourself or others where appropriate.

**Timeline**

* beta release: 1 January 2022
* GA release: 24 January 2022

**Repo Issues**

- [x] textpattern/textpattern 
  * 4.8.8 milestone: [open issues](https://github.com/textpattern/textpattern/milestone/21) & [closed issues](https://github.com/textpattern/textpattern/milestone/21?closed=1)

# Production Release

## Personnel

* Release pilot: tbc
* Release co-pilot: tbc

## Preflight

- [x] preflight
  - [x] latest translations (@philwareham)
  - [x] latest pophelp (@philwareham)
  - [x] draft .com blog post (release pilot, or assigned person)
  - [x] write `HISTORY.txt` (everyone)
    - [x] additional credits where not already listed (e.g. patched security issues) (everyone)
  - [x] top and tail `HISTORY.txt` with additional information (release pilot or co-pilot)
  - [x] tag public/admin themes with release tag (@philwareham)
  - [x] tag Textpacks and Pophelps with release tag (@philwareham)

## Take Off

- [x] take off
  - [x] package up for GitHub and .com (release pilot)
  - [x] update `latest.zip` and `latest.tar.gz` in server config (@petecooper)
  - [ ] update language pack links in server config (@petecooper)
  - [x] update demo site (@petecooper)
  - [x] publish .com blog post (release pilot, or assigned person)
  - [x] forum announcement (release pilot, or assigned person)
  - [x] forum feedback (release pilot, or assigned person)

## Inflight service

- [x] inflight service
  - [x] close milestone (release pilot, or assigned person)
  - [x] update `TXPversion` on `rpc.textpattern.com` (release pilot, or assigned person)
  - [x] update https://en.wikipedia.org/wiki/Template:Textpattern_version (@petecooper or @philwareham)
  - [x] socials (@petecooper or @philwareham)
  - [x] update https://textpattern.com/about/system-requirements to reflect PHP 8.1.0 support
  - [x] repin https://github.com/textpattern/textpattern/issues/279

**Comment by petecooper** [comment]
Looking at the plans for the [PHP 8.1.0 schedule](https://wiki.php.net/todo/php81), GA is planned to arrive November 25 2021. The issue queue for 4.8.8 is currently empty, so we have a few months to housekeep existing issues for some easy / effective wins.

With that in mind, it seems pretty straightforward to tag 4.8.8 as a PHP 8.1 maintenance release, with a few bits of tidying as we go. Should a priority release be needed in the coming months before PHP 8.1 drops, we can defer any other PHP 8.1 changes to a 4.8.9 release.

@Bloke @bloatware @philwareham Does that sound reasonable for now? Anything I've missed?

**Comment by Bloke** [comment]
Works for me. Any small wins from 4.9.0 we can bring forward?

**Comment by petecooper** [comment]
@Bloke If you have any insight into https://github.com/textpattern/textpattern/issues/1707 that might be an easy win.

There are currently 20 [issues without a milestone](https://github.com/textpattern/textpattern/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone), so perhaps a couple of passes through those to housekeep might yield some gems. I'll take a nosey after some late lunch.

**Comment by Bloke** [comment]
There is a [potential callback bug](https://forum.textpattern.com/viewtopic.php?id=51582) that needs investigating as part of this release. It's unconfirmed as yet, so no issue to track it at the moment.

**Comment by petecooper** [comment]
>Any small wins from 4.9.0 we can bring forward?

Not strictly from 4.9.0 milestone, but is there anything we can do with https://github.com/textpattern/textpattern/issues/1379 realistically?

**Comment by petecooper** [comment]
Note sure of the scope here – it may need an issue – but there's an RSS issue that has cropped up. It may be an easy win for 4.8.8: https://forum.textpattern.com/viewtopic.php?pid=331277#p331277

**Comment by bloatware** [comment]
This is not really a core issue, but we can try to do something to accommodate hacky plugins.

**Comment by petecooper** [comment]
Raising this as an RFC since we're about two months from GA: do we need a beta release for 4.8.8?

This is new territory for a patch release, but there's merit in doing the beta dance. There's some discussion about a beta in https://github.com/textpattern/textpattern/issues/1696 but I propose we have a thumbs up or thumbs down to gauge the consensus.

Knowing what we do at the current time, and given this *may* be the last release on the 4.8 circuit, should we do one or more beta releases for 4.8.8? Thumbs up for 'Yes', thumbs down for 'No'. Paging @bloatware @Bloke @philwareham for input, and any readers with an opinion either way.

Thank you.

**Comment by Bloke** [comment]
A beta seems prudent given the changeset.

**Comment by phiw13** [comment]
> A beta seems prudent […]

+9

**Comment by petecooper** [comment]
Unless there's any objection, a beta seems like the way forward. Paging @bloatware & @philwareham – please sound off if you're against the idea for any reason.

If no objection, I'll put a post in the forum, on the socials and a short .com blog post with our beta intentions.

**Comment by bloatware** [comment]
I'm fine with a beta, just thinking in two months it could get irrelevant. We are rarely keeping quiet when new ideas/requests come.

**Comment by petecooper** [comment]
>We are rarely keeping quiet when new ideas/requests come.

Oh, definitely. +1.

It's been a while since we had a beta release, and if it becomes a formality then that reinforces we were perhaps right to do it…but if there are issues uncovered, we may be able to address them easily for the GA release. Either way, there is some value to the end users (and us, because we get more practice with releases).

**Comment by phiw13** [comment]
> I'm fine with a beta, just thinking in two months it could get irrelevant. 

I would expect a putative beta to be released ~ 2 weeks before final release, not much earlier and certainly not now.

**Comment by petecooper** [comment]
@phiw13 – Agreed, I updated OP with provisional guideline dates before your post above. Would appreciate your take on this, if appropriate.

**Comment by petecooper** [comment]
@bloatware - I think the penny just dropped when I re-read my comments and your reply, then @phiw13's comments.

I should clarify: I was proposing a beta release around the time of PHP 8.1.0 GA, not now or imminently, then Textpattern 4.8.8 when we're happy it's playing nicely (let's say a few weeks later, assuming no major snags).

**Comment by petecooper** [comment]
- [ ] https://github.com/textpattern/pophelp/issues/63

**Comment by petecooper** [comment]
I've penned a straightforward blog post for 4.8.8, please see article 443 and amend as you see fit. If it's broadly OK with you, we should publish this week as we're expecting PHP 8.1.0 in about 14 days. If no objection, I'll aim for publication 0900UTC on 2021-11-11.

Please attach a thumbs up if / when you're happy with the content and optics. Thank you!

**Comment by petecooper** [comment]
https://textpattern.com/weblog/php-810-x-textpattern-cms-488

**Comment by philwareham** [comment]
Thanks as always Pete - I read that earlier and looks good to me!

**Comment by petecooper** [comment]
PHP 8.1.0 has been tagged, to be announced Thursday. Demo server is live, no explosions. 4.8.8 is a step closer.

What's left to address for the beta release?

**Comment by bloatware** [comment]
Wow, not bad. Just few tweaks/cleanups on my side, should be ready for this week-end. But one annoying issue is still [pending](https://github.com/textpattern/textpattern/issues/1748), though it seem to concern only one user :-)

**Comment by petecooper** [comment]
@bloatware @Bloke – What's your current assessment of where we're at with 4.8.8? Viable for a beta in the next 7-10 days, perhaps?

**Comment by bloatware** [comment]
There is only one diff in my local copy, so viable for me.

**Comment by petecooper** [comment]
I've been away on tour, and now I'm back. I propose:

- we freeze 4.8.8 Wednesday, December 8th 2021 (week 49).
- we release and publicise 4.8.8 beta Thursday, December 9th 2021 (week 49).
- check viability for a second beta OR go straight to GA week commencing Monday December 27th 2021 (week 52).

@Bloke - would you prefer to run beta or GA release? I'll offer to do the other.

**Comment by philwareham** [comment]
I can help with the release a bit - getting the latest translations in and tagging theme releases , as usual. Hopefully New Year I can spare a few more hours to fix some bits in 4.9 admin panels that's been on my list for a while.

**Comment by bloatware** [comment]
@petecooper could you please set `Debug` as default mode?

**Comment by petecooper** [comment]
@bloatware yes - leave that with me for now, I will report back when ready.

**Comment by petecooper** [comment]
@bloatware - debug mode now enabled on 4.8.8 dev demo.

**Comment by bloatware** [comment]
@petecooper cool, thanks. Hope we will quickly get rid of the remaining php 8.1 surprises.

**Comment by bloatware** [comment]
Meanwhile, the public side looks borked.

**Comment by Bloke** [comment]
Urk, what's all that `date_default_timezone_set()` junk about?

**Comment by Bloke** [comment]
Maybe `date_default_timezone_get()` is at fault because the value isn't set properly in php.ini and it's passing that on to `date_default_timezone_set()` verbatim. If so, we should defend against that somehow. Is that even possible?

**Comment by bloatware** [comment]
Possibly related: `Fatal error: Uncaught Error: Undefined constant "LANG"` on the public side?

**Comment by Bloke** [comment]
Yes, I wondered about that. I think it's a by-product of calling something else before we include publish.php, which is where `LANG` is defined. Even making reference to `gTxt()` prior to that or trying to load/switch some language strings would trigger the error. Can't see where that would occur though from a cursory glance through the code.

**Comment by bloatware** [comment]
This one should be fixed now, TBC.

**Comment by Bloke** [comment]
Ha! No way, the error handler itself using `gTxt()`. Well spotted.

**Comment by Bloke** [comment]
Incidentally, this means we can get rid of the general_error lang string from the Textpacks.

**Comment by petecooper** [comment]
Checking in. How are we placed for a first beta, sirs? I respectfully propose we feature-freeze for beta 1 now or very soon and push a release out for testing, then if we need to roll a second in due course, we can do that. Does that sound reasonable?

**Comment by bloatware** [comment]
I have installed php 8.1 and spotted few extra bugs (now patched). There is still #1748 pending... @Bloke ?

**Comment by petecooper** [comment]
@bloatware @Bloke @philwareham 

We need to get 4.8.8 out soon. We've got a lot of stuff that's changed, PHP 8.1 support has been added, and we're *SO CLOSE NOW*. The Textpattern feature creep is starting to rear its head. Can we get a 4.8.8 beta out before year-end? We can do a second beta if issues arise, but we need to get something out soon-ish. The sooner we can get a beta out for testing, the more likely we'll have real world feedback…plus, we need to release more…our stuff is _good_ and we need to shout louder.

Where we go after 4.8.8 depends on you folks. Do we have enough patch-level stuff to work into a 4.8.9 release, or do we gun for a 4.9.0 release (factoring in the time taken for that to be ready)? If there's a 4.8.9 to catch snags, that's cool – but it'd be useful to know either way, so we can nail issues to the appropriate mast.

Thank you!

**Comment by philwareham** [comment]
I've fixed the only thing that was on the 4.8.8 list for me, and have brought in the latest translations. So, from my side, 4.8.8 can beta release whenever you guys want.

Regarding 4.8.9 vs. 4.9.0 I'd rather go with the latter now and draw a line under 4.8.x development. It's more work keeping two codebases running in tandem.

**Comment by petecooper** [comment]
As a godless heathen, I have no holiday plans. I can push a beta out before the new year if we're broadly ready. That will give us some eyeballs for testing and we can investigate https://github.com/textpattern/textpattern/issues/1748 (and whatever else) as needed once it's out.

**Comment by bloatware** [comment]
Could you mac users test php 8.1 for avif support?

**Comment by phiw13** [comment]
What more would you want to know than what is already said ?

If the browser supports that  image format, you can upload an image. The dimensions are unknown (or zero), there is no thumbnail generation, automatically or manually. And I don’t think you can expect that to work for now given the [PHP issue](https://github.com/php/php-src/commit/38460c2c94a0d4b110060951a1a56575226adbfc) you linked to.

**Comment by bloatware** [comment]
Are there any warnings on upload yet? And how @<txp:images />@ tag works with zero dimensions? Can you filter by @height/width/ratio@?

**Comment by Bloke** [comment]
I'm tempted to ignore #1748 until post-beta. I can't for the life of me think why it's doing it (and my STR aren't quite right anyway so I'll need to amend those if the issue still holds water) so it's probably either environment-specific or PHP-version specific. Either way there's a chance someone else may be able to replicate it, so let's not wait.

**Comment by phiw13** [comment]
No warnings on file upload anymore The tag`<txp:images />` itself I tested and it works as it doesn’t specify any width/height (e.g `<txp:images id="2" />`); this displays the full-size image in a default install. As for the rest I will see if I can test on Saturday – I doubt I’ll have energy and time earlier. Sorting based on  width and height would not work (fall back to default ?) given that all is `0`.

**Comment by phiw13** [comment]
Avif  – Sorting by width/height:

* mix of various formats: the avif files always come first or last (zero width/height)
* 3 avif files: sorted by `ID`

The images are displayed at their intrinsic size (exif data read by the browser) constrained by whatever the stylesheet has to say (`max-width`, …) No warning or errors flagged in debug mode.


```
<txp:images  sort="w desc" />
```

with images listed in the article image field or with images listed in the `ID` attribute

**Comment by petecooper** [comment]
We need to release this soon.

Barring any objections, let's aim for Jan 1st 2022 for `beta.1`. I'll volunteer as beta release-r, unless @Bloke has any objections.

@bloatware - do we need to merge anything from https://github.com/textpattern/textpattern/pull/792 or would you prefer to wait until after 4.8.8 is GA?

@philwareham - you're off the hook, I think your stuff is all up-to-date. The usual game of who can get to change the copyright dates on Jan 1st is still on…

Assign thumbs up for a Jan 1st beta or thumbs down for any objections, please and thank you.

**Comment by Bloke** [comment]
Jan 1st is fine by me. Happy for you to take the beta release reins on this one, thank you @petecooper

**Comment by petecooper** [comment]
OK, dates bumped to '22, starting beta run.

@bloatware @Bloke @philwareham - tools down, please & thanks.

**Comment by petecooper** [comment]
![5zpbtq](https://user-images.githubusercontent.com/226578/147853337-4cb62db6-3160-42b3-a6db-80bb587d10e8.jpg)

**Comment by petecooper** [comment]
@bloatware @Bloke @philwareham

How does Jan 21st sound for a full release? Any beta feedback we need to address? Anything we can squeeze in without getting into feature creep?

I don't have the skills to look into https://github.com/textpattern/textpattern/issues/1774 as I'm not familiar with multisite, any thoughts on that?

**Comment by philwareham** [comment]
Sounds fine to me!

**Comment by bloatware** [comment]
If #1774 is confirmed, we should fix it first, imo.

**Comment by petecooper** [comment]
I may have some time this evening to have a look at multisite, I've never used it in anger so it'll be a good exercise.

**Comment by bloatware** [comment]
@petecooper that would be great, thank you. I have tried, but failed to make it work.

**Comment by petecooper** [comment]
>If #1774 is confirmed, we should fix it first, imo.

It appears to be a docs / procedural issue not code.

**Comment by petecooper** [comment]
I can run the 4.8.8 release unless there are any objections.
@Bloke - please shout if you want dibs and/or a co-pilot.

Last and final boarding call, any reasons to NOT release today?

**Comment by Bloke** [comment]
Are we happy with the resolution of #1774 then? Is it worth fixing #1775 first?

**Comment by Bloke** [comment]
Yeah, I'm not sure either. #1775 is kind of an oversight when we introduced the /textpattern/plugins directory. Arguably a bug because we're implying that your shared textpattern base install has to have the same plugins in all sites, since they're served from a central location. It's far better to have the plugin path cognisant of the constant so people can move the plugins _out_ of the central area and into one of the per-site directories by simply (re)defining it in config.php. Adds flexibility. I can't see any backwards compatibility issue with @jools-r 's [proposed patch](https://github.com/textpattern/textpattern/issues/1775#issuecomment-1018863568)

**Comment by petecooper** [comment]
>I can't see any backwards compatibility issue with @jools-r 's proposed patch

Ah, OK - if it's that straightforward then perhaps it's an easy win.

**Comment by petecooper** [comment]
FYI, anticipating a PR from @jools-r to address https://github.com/textpattern/textpattern/issues/1775 so release will realistically be tomorrow or after.

**Comment by petecooper** [comment]
Issue queue is clear, time for us to get this sucker out, I think.

Dibs unless @Bloke wants to run it. ETA: today (Monday, January 24th 2022) unless anyone says so.

Paging @philwareham & @bloatware - happy to proceed?

**Comment by philwareham** [comment]
Yes, I'm happy to go. Will check Crowdin to see if any new translations need to be added to the Textpacks and Pophelp - then we can tag those repos for release. I'll also tag the themes and admin themes when you are ready to proceed.

**Comment by Bloke** [comment]
Yay. Let's do this thing. Happy for you to run it, thank you. We probably just want to mention in the release notes the potential backwards-compatibility issue with multi-site plugins dir.

**Comment by petecooper** [comment]
>backwards-compatibility issue with multi-site plugins dir

@Bloke - is that something you can do, please? Assume I'm a thick-o.

**Comment by petecooper** [comment]
Will start the release at 1300UTC, tools down 1245UTC latest, please and thanks.

Gitter is open for any backchannel comms.

**Comment by Bloke** [comment]
[History updated](https://github.com/textpattern/textpattern/commit/c2dc7d56a60ca77c41aa0fd3908c4e1efffaf907)

**Comment by petecooper** [comment]
Tools down, sirs. Showtime!

**Comment by philwareham** [comment]
I just need to make sure admin themes are tagged properly. 5 mins.

**Comment by philwareham** [comment]
OK, go for it!

**Comment by petecooper** [comment]
https://github.com/textpattern/textpattern/releases/tag/4.8.8

Nearly done…

**Comment by petecooper** [comment]
I think we're looking at a 4.8.9 before 4.9.0 hits the shelves. PHP minor releases are yearly, and if we're aiming for support then we should expect beta + release candidates from early summer onwards, release end of November 2022 - 10 months-ish away.

So, do we spin `4.8.8` branch into `4.8.9` now? Need to know before I wrap up the release process, since the toolkit assumes `dev` is the way forward. For what it's worth, `main` is up to date…so perhaps better to spin _that_ out to `4.8.9` instead?

Paging @bloatware, @Bloke & @philwareham for guidance.

**Comment by philwareham** [comment]
I'd rather move on from 4.8.x branch now - more work keeping two branches in sync.

**Comment by petecooper** [comment]
Fair point. It would be straightforward enough to spin a branch off `main` when PHP 8.2 stuff needs changes, I guess. We're not gonna have 4.9 ready this year, if we're using past release series as a timeline guide, that's my concern.

**Comment by Bloke** [comment]
Yeah, if we need 4.8.9, we can spin it off `main`. Once everything's merged to main, and we're happy everything's sorted, v4.8.8. can be axed.

**Comment by petecooper** [comment]
Waiting comms from Paul at Pentest re: co-ordinated release of blog posts. ETA: 4pm. Assuming that goes to plan, I'll wrap up loose ends and we're done.

**Comment by petecooper** [comment]
Our sites are updated, release post goes live 1600UTC (two mins), I'll wrap up the rest of the stuff and we're done.

**Comment by petecooper** [comment]
Boom:

https://textpattern.com/weblog/textpattern-488-released-php-81-support-security-fix-and-more

**Comment by philwareham** [comment]
Cheers Pete - great stuff. I cleared the cache at Cloudflare just to ensure the blog article appears for everyone (we have quite an aggressive cache there).

**Comment by petecooper** [comment]
Done.

**Comment by Bloke** [comment]
Super work everyone, and thanks Pete for taking the reins on the release. Another fabulous addition to the Textpattern release line.
