### ISSUE TITLE
Textpattern 4.8.9 release flight plan

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1845]
We are targeting Textpattern 4.8.9 for release in Q4 2022 or Q1 2023 to provide initial support for PHP 8.2, address some snags, and provide further refinements. The release flight plan includes at least one beta release before the production release.

* [4.8.9 branch](https://github.com/textpattern/textpattern/tree/v4.8.9)

Please update this post and subsequent replies with tasks etc as needed, assigning yourself or others where appropriate.

**Timeline**

* beta release: Q4 2022 or Q1 2023
* GA release: Q4 2022 or Q1 2023

**Repo Issues**

# Production Release

## Personnel

* Release pilot: tbc
* Release co-pilot: tbc

## Preflight

- [ ] preflight
  - [ ] latest translations (@philwareham)
  - [ ] latest pophelp (@philwareham)
  - [ ] draft .com blog post (release pilot, or assigned person)
  - [ ] write `HISTORY.txt` (everyone)
    - [ ] additional credits where not already listed (e.g. patched security issues) (everyone)
  - [ ] top and tail `HISTORY.txt` with additional information (release pilot or co-pilot)
  - [ ] tag public/admin themes with release tag (@philwareham)
  - [ ] tag Textpacks and Pophelps with release tag (@philwareham)

## Take Off

- [ ] take off
  - [ ] package up for GitHub and .com (release pilot)
  - [ ] update `latest.zip` and `latest.tar.gz` in server config (@petecooper)
  - [ ] update language pack links in server config (@petecooper)
  - [ ] update demo site (@petecooper)
  - [ ] publish .com blog post (release pilot, or assigned person)
  - [ ] forum announcement (release pilot, or assigned person)
  - [ ] forum feedback (release pilot, or assigned person)

## Inflight service

- [ ] inflight service
  - [ ] close milestone (release pilot, or assigned person)
  - [ ] update `TXPversion` on `rpc.textpattern.com` (release pilot, or assigned person)
  - [ ] update https://en.wikipedia.org/wiki/Template:Textpattern_version (@petecooper or @philwareham)
  - [ ] socials (@petecooper or @philwareham)
  - [ ] update https://textpattern.com/about/system-requirements to reflect PHP 8.2.0 support

**Comment by jools-r** [comment]
The inevitable question :-)
Can 4.8.9 also include some updates that are not part of the more major admin-side revisions in 4.9? Just by way of example, on the main branch of my fork, I keep a kind of 4.8.8++ version going with mini bugfixes and minor but useful additions. Mostly these are fixes by Oleg or things I've encountered and submitted as PRs.
I'd love to see things like phpmailer, perhaps even the CSP headers, be incorporated as well… but maybe I'm just impatient!

**Comment by Bloke** [comment]
And change the version string :)

**Comment by philwareham** [comment]
Ok, I think I can spare some time to make this happen.

**Comment by Bloke** [comment]
> So `dev` = the 4.8.9 release branch, saves us from branch juggling by making a `4.8.9` branch…is that appropriate?

Don't see why not. It shouldn't break anybody's experience since it's marked as dev anyway. Just needs the version strings updating, which might piss off git but it's easily resolvable by hand if it complains.

**Comment by jools-r** [comment]
Wooh, I'd be glad to see the dev branch as the next release 🎉

Next inevitable question: why not go straight to 4.9 if it's going to be more than just bugfixes?

**Comment by philwareham** [comment]
Note to all. There's a few UI things in the dev branch I half did and would need finishing before that can be released (mainly around the 'save' button area and how it collapses on mobile). I'd need to revert some of that or finish it properly.

**Comment by philwareham** [comment]
Otherwise, you could certainly do a 4.9 release. Other software does point versions with a lot less features per release than we do!

**Comment by Bloke** [comment]
I'm fine with 4.9.

**Comment by petecooper** [comment]
I'm torn on this. On one hand, taking `main`, branching to `4.8.9` and applying the PHP 8.2 patches (plus some easy wins) gets a tick in the box for compatibility. It feels a bit wasteful to undo the 4.9 work that's gone into `dev`, and the PHP minimum ride height may catch out plugins on the outer edges…plus there's also https://github.com/textpattern/textpattern/issues/1781 which should be factored in, because if we shoot for 4.9 in 2023 we can sack off PHP 5 and possible veeeery early PHP 7 completely.

That said, there are 1100+ commits to `dev` from `main` which is no small task to sift through. I realise development has been a little slower pace this year, so it could be a much bigger task. Peeling off the PHP 8.2 changes and some easy wins would be doable, but I'll go with the consensus.

**Comment by Bloke** [comment]
There have been some big changes to the plugins panel as well to prepare for the seamless upgrade notifications. That's pretty major. And nothing to stop us making a few tweaks to add upgrade notices on that panel now.

**Comment by petecooper** [comment]
Revisiting this so we can plan for next week's launch…

It feels a bit short notice to go straight to 4.9 _unless_ we factor in the following:

* at least one beta and RC
* acknowledge and advise that not all "new" stuff will be ready the "point zero" release

My gut feeling says shoot for a 4.8.9 and use that as the last release in the 4.8 series (barring any security fuckery), then refocus on getting 4.9.0 ready prior to _PHP Winter 2023 Remix_ and have enough time to test all the new stuff.

If it's just too much of a headache to unpick the non-PHP stuff, perhaps the smart money would be to leave PHP 8.2 changes in `dev` and shoot for a beta in 2023Q1 instead. I'm very aware of your collective workloads and life responsibilities, so let's be realistic – a month or three delay for PHP 8.2 support affects close to zero people in real terms, whereas a smooth 4.9.0 release would positively affect a lot more people.

My 2c with the visibility I have. What do you think?

**Comment by bloatware** [comment]
Me thinks PHP 8.2 stuff can wait, but there are few annoying bugs in 4.8.8 (`.txt` plugins install on PHP 5 and `<txp:image />` height/width regression) that should be patched. Can we fork of `main` and release 4.8.9 with minimal hand-made modifications, or is it a complete nonsense?

**Comment by phiw13** [comment]
If you go for a very minimal release, can you at least including an absolute minimal fix for issue 1840 (`aria-label` that prevent screen readers  reading title etc) – just remove them on the list panels  (articles/images/categories).

**Comment by philwareham** [comment]
I can look at the `aria-label` removal later today, I think.

**Comment by bloatware** [comment]
Actually, even PHP 8.2 patches can be integrated into 4.8.9, to justify its release.

**Comment by jools-r** [comment]
> Me thinks PHP 8.2 stuff can wait, but there are few annoying bugs in 4.8.8 (`.txt` plugins install on PHP 5 and `<txp:image />` height/width regression) that should be patched. Can we fork of `main` and release 4.8.9 with minimal hand-made modifications, or is it a complete nonsense?

This is kind of what I've been doing for myself at https://github.com/jools-r/textpattern. It's mostly incorporating your commits and a few things I needed/wanted. It lacks all the new UI stuff on the admin-side, though, as well as other quite nice stuff like PHPmailer that would be really useful in a new update, and I've been recreating your commits manually so probably inexpertly done. Long story short, however, I don't think that's nonsense if making all the 4.9 inclusions for the next update is unrealistic.

**Comment by Bloke** [comment]
@philwareham How much effort is required to make the dev save panel tweaks workable on mobile?

Going through dev and cherry picking a bunch of commits into a 4.8.9 release seems a bit wasteful when dev hasn't had any fewer eyes and testers than any other release cycle. I've been running it on production sites for yonks.

The PHPMailer integration is solid, com_connect is primed ready to bolt onto it. The plugin panel upload improvements, with its better security aspect and the fact everything goes through the verify step, makes me much happier. The bug fixes bloatware noted with the plugin .txt uploads too. Plus all the other fab things rolled in so far, like SVG image handling, the self-closing validator fixes, CSP headers, and the UI library which core and plugin authors can start using.

Why not just release dev as 4.9.0-beta next week? Is that unrealistic?

**Comment by philwareham** [comment]
I'd rather release 4.9 than a minor point release, there's enough there to warrant a major point release.

I can work on the admin theme fixes during this coming week, yes. Then happy for a beta.

**Comment by petecooper** [comment]
OK, so consensus is tending toward 4.9 release process instead of 4.8.9.

If that is the case, then this thread can be closed since we need a different plan for a non-patch release, and there are more considerations in the release process.

Please mark this comment with a thumbs up for a 4.9.0 release or a thumbs down for a 4.8.9 release , and we can get on the right track.

**Comment by bloatware** [comment]
Do we push [SVG support](https://github.com/textpattern/textpattern/pull/1848) into 4.9? IIRC, @philwareham had plans for enabling image editing in txp, but I'm unsure how it would work for .svg images.

**Comment by jools-r** [comment]
I'd love to see SVG upload support, especially when the svg width and height is stored with the image. SVG image editing would, I guess, only be possible as code editing, and certainly different to pixel images.

**Comment by petecooper** [comment]
I'm gonna close this for now since it's a flight plan for a patch release, and we're aiming for a minor on next run. I'll make sure we don't lose sight of comments when I open the new flight plan. Thanks for your all your invaluable input, folks.
